# Generated by Django 5.2.1 on 2025-06-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_create_event', 'Può creare eventi')]},
        ),
    ]
