# Generated by Django 5.2.1 on 2025-07-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_create_event', 'Può creare eventi'), ('can_view_created_events', 'Può vedere eventi organizzati'), ('can_view_attendees_list', 'Può vedere gli iscritti a un evento')]},
        ),
    ]
