# Generated by Django 5.2.1 on 2025-07-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_view_all_events', 'Può vedere tutti gli eventi'), ('can_register_for_event', 'Può registrarsi a un evento'), ('can_unregister_from_event', 'Può annullare la registrazione a un evento'), ('can_view_own_registrations', 'Può vedere le proprie registrazioni'), ('can_create_event', 'Può creare eventi'), ('can_delete_event', 'Può eliminare eventi'), ('can_edit_event', 'Può modificare eventi'), ('can_view_created_events', 'Può vedere eventi organizzati'), ('can_view_attendees_list', 'Può vedere gli iscritti a un evento')]},
        ),
    ]
